export const endpoints = {
  auth: {
    login: "/api/v1/auth/login",
    register: "/api/v1/auth/register",
    refresh: "/api/v1/auth/refresh",
    logout: "/api/v1/auth/logout",
    me: "/api/v1/auth/me",
    forgotPassword: "/api/v1/auth/forgot-password",
    resetPassword: "/api/v1/auth/reset-password",
    verifyEmail: "/api/v1/auth/verify-email",
    resendVerification: "/api/v1/auth/resend-verification",
    verifyResetCode: "/api/v1/auth/verify-reset-code",
    changeEmail: "/api/v1/auth/change-email",
  },
  tutors: {
    applications: "/api/v1/tutors/applications",
    myApplication: "/api/v1/tutors/applications/me",
    byId: (id: string | number): string => `/api/v1/tutors/${id}`,
    availability: "/api/v1/availability",
    availabilityById: (id: string | number): string => `/api/v1/availability/${id}`,
    availabilityByTeacher: (id: string | number): string => `/api/v1/tutors/${id}/availability`,
  },
  users: {
    me: "/api/v1/users/me",
    byId: (id: string | number): string => `/api/v1/users/${id}`,
    update: "/api/v1/users/me",
    avatar: "/api/v1/users/me/avatar",
    tutors: "/api/v1/users/tutors",
  },
  courses: {
    list: "/api/v1/courses",
    popular: "/api/v1/courses/popular",
    byId: (id: string | number): string => `/api/v1/courses/${id}`,
    create: "/api/v1/courses",
    update: (id: string | number): string => `/api/v1/courses/${id}`,
    delete: (id: string | number): string => `/api/v1/courses/${id}`,
    byTeacher: (id: string | number): string => `/api/v1/courses/teacher/${id}`,
    canReview: (courseId: string | number): string => `/api/v1/courses/${courseId}/can-review`,
  },
  search: {
    courses: "/api/v1/search/courses",
    coursesV2: "/api/v1/search/courses/v2",
    suggestions: "/api/v1/search/suggestions",
    tutors: "/api/v1/search/tutors",
  },
  reviews: {
    list: (courseId: string | number): string => `/api/v1/courses/${courseId}/reviews`,
    create: (courseId: string | number): string => `/api/v1/courses/${courseId}/reviews`,
    createForBooking: (courseId: string | number, bookingId: string | number): string =>
      `/api/v1/courses/${courseId}/reviews/booking/${bookingId}`,
  },
  bookings: {
    create: "/api/v1/bookings",
    byId: (id: string | number): string => `/api/v1/bookings/${id}`,
    confirm: (id: string | number): string => `/api/v1/bookings/${id}/confirm`,
    reject: (id: string | number): string => `/api/v1/bookings/${id}/reject`,
    cancel: (id: string | number): string => `/api/v1/bookings/${id}/cancel`,
    complete: (id: string | number): string => `/api/v1/bookings/${id}/complete`,
    my: "/api/v1/bookings/me",
    teacher: "/api/v1/bookings/teacher",
  },
  enrollments: {
    enroll: (courseId: string | number): string => `/api/v1/courses/${courseId}/enroll`,
    myEnrollments: "/api/v1/students/me/enrollments",
    tutorRequests: "/api/v1/tutors/me/requests",
    byId: (id: string | number): string => `/api/v1/enrollments/${id}`,
    accept: (id: string | number): string => `/api/v1/enrollments/${id}/accept`,
    acceptAndSchedule: (id: string | number): string => `/api/v1/enrollments/${id}/accept-and-schedule`,
    reject: (id: string | number): string => `/api/v1/enrollments/${id}/reject`,
    requestInfo: (id: string | number): string => `/api/v1/applications/${id}/request-info`,
    provideInfo: (id: string | number): string => `/api/v1/applications/${id}/submit-info`,
    cancel: (id: string | number): string => `/api/v1/enrollments/${id}`,
    forCourse: (courseId: string | number): string => `/api/v1/courses/${courseId}/enrollment`,
  },
  applications: {
    requestInfo: (id: string | number): string => `/api/v1/applications/${id}/request-info`,
    submitInfo: (id: string | number): string => `/api/v1/applications/${id}/submit-info`,
    byId: (id: string | number): string => `/api/v1/applications/${id}`,
    timeline: (id: string | number): string => `/api/v1/applications/${id}/timeline`,
  },
  schedule: {
    propose: (applicationId: string | number): string => `/api/v1/schedule/applications/${applicationId}/propose`,
    proposals: (applicationId: string | number): string => `/api/v1/schedule/applications/${applicationId}/proposals`,
    proposal: (id: string | number): string => `/api/v1/schedule/proposals/${id}`,
    accept: (id: string | number): string => `/api/v1/schedule/proposals/${id}/accept`,
    reject: (id: string | number): string => `/api/v1/schedule/proposals/${id}/reject`,
    counter: (id: string | number): string => `/api/v1/schedule/proposals/${id}/counter`,
    my: "/api/v1/schedule/me",
    byId: (id: string | number): string => `/api/v1/schedule/${id}`,
    lessons: (id: string | number): string => `/api/v1/schedule/${id}/lessons`,
    availableSlots: (applicationId: string | number): string =>
      `/api/v1/schedule/applications/${applicationId}/available-slots`,
    checkAvailability: "/api/v1/schedule/check-availability",
  },
  lessons: {
    list: "/api/v1/lessons",
    byId: (id: string | number): string => `/api/v1/lessons/${id}`,
    dto: (id: string | number): string => `/api/v1/lessons/${id}/dto`,
    create: "/api/v1/lessons",
    cancel: (id: string | number): string => `/api/v1/lessons/${id}/cancel`,
    complete: (id: string | number): string => `/api/v1/lessons/${id}/complete`,
    start: (id: string | number): string => `/api/v1/lessons/${id}/start`,
    studentNoShow: (id: string | number): string => `/api/v1/lessons/${id}/student-no-show`,
    tutorNoShow: (id: string | number): string => `/api/v1/lessons/${id}/tutor-no-show`,
    issue: (id: string | number): string => `/api/v1/lessons/${id}/issue`,
    join: (id: string | number): string => `/api/v1/lessons/${id}/join`,
    review: (id: string | number): string => `/api/v1/lessons/${id}/review`,
    details: (id: string | number): string => `/api/v1/lessons/${id}/details`,
    reschedulePropose: (id: string | number): string => `/api/v1/lessons/${id}/reschedule/propose`,
    rescheduleAccept: (id: string | number): string => `/api/v1/lessons/${id}/reschedule/accept`,
    rescheduleReject: (id: string | number): string => `/api/v1/lessons/${id}/reschedule/reject`,
    reschedule: (id: string | number): string => `/api/v1/lessons/${id}/reschedule`,
    formatPropose: (id: string | number): string => `/api/v1/lessons/${id}/format/propose`,
    formatAccept: (id: string | number): string => `/api/v1/lessons/${id}/format/accept`,
    formatReject: (id: string | number): string => `/api/v1/lessons/${id}/format/reject`,
    locationPropose: (id: string | number): string => `/api/v1/lessons/${id}/location/propose`,
    locationAccept: (id: string | number): string => `/api/v1/lessons/${id}/location/accept`,
    locationReject: (id: string | number): string => `/api/v1/lessons/${id}/location/reject`,
    durationPropose: (id: string | number): string => `/api/v1/lessons/${id}/duration/propose`,
    durationAccept: (id: string | number): string => `/api/v1/lessons/${id}/duration/accept`,
    durationReject: (id: string | number): string => `/api/v1/lessons/${id}/duration/reject`,
  },
  calendar: {
    range: (from: string, to: string, tz?: string): string =>
      `/api/v1/calendar?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}&tz=${encodeURIComponent(tz ?? "")}`,
  },
  messages: {
    conversations: "/api/v1/messages/conversations",
    conversation: (id: string | number): string => `/api/v1/messages/conversations/${id}`,
    send: "/api/v1/messages",
    attachments: "/api/v1/messages/attachments",
    reaction: (messageId: string | number): string => `/api/v1/messages/${messageId}/reactions`,
    reactions: (messageId: string | number): string => `/api/v1/messages/${messageId}/reactions`,
    reply: (messageId: string | number): string => `/api/v1/messages/${messageId}/reply`,
    edit: (messageId: string | number): string => `/api/v1/messages/${messageId}`,
    delete: (messageId: string | number): string => `/api/v1/messages/${messageId}`,
    forward: (messageId: string | number): string => `/api/v1/messages/${messageId}/forward`,
    markRead: (conversationId: string | number): string => `/api/v1/messages/conversations/${conversationId}/read`,
  },
  meetings: {
    token: (bookingId: string | number): string => `/api/v1/bookings/${bookingId}/meeting/token`,
    end: (bookingId: string | number): string => `/api/v1/bookings/${bookingId}/meeting/end`,
  },
  notifications: {
    list: "/api/v1/notifications",
    unreadCount: "/api/v1/notifications/unread-count",
    markRead: (id: string | number): string => `/api/v1/notifications/${id}/read`,
    markAllRead: "/api/v1/notifications/read-all",
  },
  support: {
    tickets: "/api/v1/support/tickets",
    ticket: (id: string | number): string => `/api/v1/support/tickets/${id}`,
    messages: (id: string | number): string => `/api/v1/support/tickets/${id}/messages`,
    send: (id: string | number): string => `/api/v1/support/tickets/${id}/messages`,
    markRead: (id: string | number): string => `/api/v1/support/tickets/${id}/read`,
    close: (id: string | number): string => `/api/v1/support/tickets/${id}/close`,
    reopen: (id: string | number): string => `/api/v1/support/tickets/${id}/reopen`,
  },
  adminSupport: {
    tickets: "/api/v1/admin/support/tickets",
    ticket: (id: string | number): string => `/api/v1/admin/support/tickets/${id}`,
    assign: (id: string | number): string => `/api/v1/admin/support/tickets/${id}/assign`,
    take: (id: string | number): string => `/api/v1/admin/support/tickets/${id}/take`,
    status: (id: string | number): string => `/api/v1/admin/support/tickets/${id}/status`,
    priority: (id: string | number): string => `/api/v1/admin/support/tickets/${id}/priority`,
    agents: "/api/v1/admin/support/agents",
  },
  admin: {
    users: "/api/v1/admin/users",
    block: (id: string | number): string => `/api/v1/admin/users/${id}/block`,
    unblock: (id: string | number): string => `/api/v1/admin/users/${id}/unblock`,
    role: (id: string | number): string => `/api/v1/admin/users/${id}/role`,
    verify: (id: string | number): string => `/api/v1/admin/users/${id}/verify`,
    stats: "/api/v1/admin/stats",
    tutors: "/api/v1/admin/tutors",
    approveTutor: (id: string | number): string => `/api/v1/admin/tutors/${id}/approve`,
    rejectTutor: (id: string | number): string => `/api/v1/admin/tutors/${id}/reject`,
    courses: "/api/v1/admin/courses",
    approveCourse: (id: string | number): string => `/api/v1/admin/courses/${id}/approve`,
    rejectCourse: (id: string | number): string => `/api/v1/admin/courses/${id}/reject`,
    reviews: "/api/v1/admin/reviews",
    hideReview: (id: string | number): string => `/api/v1/admin/reviews/${id}/hide`,
    restoreReview: (id: string | number): string => `/api/v1/admin/reviews/${id}/restore`,
    reports: "/api/v1/admin/reports",
    updateReport: (id: string | number): string => `/api/v1/admin/reports/${id}`,
  },
} as const;

export const pageParams = (page = 0, size = 20): string => `page=${page}&size=${size}`;

export type Endpoints = typeof endpoints;
